# Generated by Django 3.0 on 2019-04-29 01:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acct_num', models.CharField(help_text='20 numeric number include dashes', max_length=20, verbose_name='Account Number')),
                ('stbmodel', models.CharField(help_text='Enter a set top box model (e.g. Hopper 813)', max_length=200)),
                ('rid', models.CharField(help_text='10 numeric starting from R', max_length=10, verbose_name='Receiver ID')),
                ('sid', models.CharField(help_text='10 numeric starting from S', max_length=10, verbose_name='Smart Card ID')),
                ('notes', models.TextField(help_text='Notes', max_length=1000)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Owner')),
            ],
        ),
    ]
