# Generated by Django 3.0 on 2019-04-29 02:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='security_status',
            field=models.CharField(default='secure', help_text='Type Secured or Unsecured', max_length=100),
            preserve_default=False,
        ),
    ]
