# Generated by Django 3.0 on 2019-04-27 19:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='STBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stbmodel', models.CharField(help_text='Enter a set top box model (e.g. Hopper 813)', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Owner', models.CharField(max_length=200)),
                ('notes', models.TextField(help_text='Notes', max_length=1000)),
                ('acct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Account')),
                ('stbmodel', models.ManyToManyField(help_text='Select a receiver', to='inventory.STBModel')),
            ],
        ),
    ]
