# Generated by Django 3.0 on 2019-04-28 19:37

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(help_text='Notes', max_length=1000)),
                ('acct_num', models.CharField(help_text='20 numeric number include dashes', max_length=20, verbose_name='Account Number')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='STBModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stbmodel', models.CharField(help_text='Enter a set top box model (e.g. Hopper 813)', max_length=200)),
                ('rid', models.CharField(help_text='10 numeric starting from R', max_length=10, verbose_name='Receiver ID')),
                ('sid', models.CharField(help_text='10 numeric starting from S', max_length=10, verbose_name='Smart Card ID')),
            ],
        ),
        migrations.CreateModel(
            name='AccountInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Owner'),
        ),
        migrations.AddField(
            model_name='account',
            name='stbmodel',
            field=models.ManyToManyField(help_text='Select a receiver', to='inventory.STBModel'),
        ),
    ]
