# Generated by Django 3.0 on 2019-04-28 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='stbmodel',
        ),
        migrations.AddField(
            model_name='accountinstance',
            name='stbmodel',
            field=models.ManyToManyField(help_text='Select a receiver', to='inventory.STBModel'),
        ),
    ]
