# Generated by Django 3.0 on 2019-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rid',
            field=models.CharField(default=0, help_text='10 numeric starting from R', max_length=10, verbose_name='Receiver ID'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='account',
            name='sid',
            field=models.CharField(default=0, help_text='10 numeric starting from S', max_length=10, verbose_name='Smart Card ID'),
            preserve_default=False,
        ),
    ]
