# Generated by Django 3.0 on 2019-04-27 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20190427_1331'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='rid',
        ),
        migrations.AddField(
            model_name='stbmodel',
            name='rid',
            field=models.CharField(default=0, help_text='10 numeric starting from R', max_length=10, verbose_name='Receiver ID'),
            preserve_default=False,
        ),
    ]
