# Generated by Django 3.0 on 2019-04-27 20:25

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20190427_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.RemoveField(
            model_name='account',
            name='Owner',
        ),
        migrations.RemoveField(
            model_name='account',
            name='sid',
        ),
        migrations.AddField(
            model_name='stbmodel',
            name='sid',
            field=models.CharField(default=0, help_text='10 numeric starting from S', max_length=10, verbose_name='Smart Card ID'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='AccountInstance',
            fields=[
                ('acct_num', models.UUIDField(default=uuid.uuid4, help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False)),
                ('account', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Account')),
            ],
        ),
    ]
