# Generated by Django 3.0 on 2019-04-27 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_auto_20190427_1425'),
    ]

    operations = [
        migrations.RenameField(
            model_name='accountinstance',
            old_name='acct_num',
            new_name='id',
        ),
        migrations.RemoveField(
            model_name='account',
            name='acct',
        ),
        migrations.AddField(
            model_name='account',
            name='Owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.Owner'),
        ),
    ]
