# Generated by Django 3.0 on 2019-04-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_auto_20190427_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='acct_num',
            field=models.CharField(default=0, help_text='16 numeric code', max_length=16, verbose_name='Account Number'),
            preserve_default=False,
        ),
    ]
