# Generated by Django 3.0 on 2019-04-27 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_account_acct_num'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='Owner',
            new_name='owner',
        ),
    ]
