# Generated by Django 3.0 on 2019-04-28 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_auto_20190427_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='acct_num',
            field=models.CharField(help_text='20 numeric number include dashes', max_length=20, verbose_name='Account Number'),
        ),
    ]
