# Generated by Django 2.2 on 2019-04-25 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_language1'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='language1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.Language1'),
        ),
    ]
