# Generated by Django 2.2 on 2019-04-25 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_book_language1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language1',
        ),
        migrations.DeleteModel(
            name='Language1',
        ),
    ]
